[package]
name = "homie-sak"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = "4.5.15"
homie-device = "0.9.0"
rumqttc = "0.22.0"
rumqttd = "0.19.0"
tokio = { version = "1.39.2" , features = [ "rt-multi-thread" ]}
